name: test zad3_1.py

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: install pytest
      run: |
        pip install -U pytest
      - run: python3 -m 
    - name: test
      run: |
        pytest zad3_1.py
